FROM alpine:latest
RUN apk add --no-cache git bash gcompat libstdc++
RUN apk add cmake build-base
RUN apk add sqlite-dev readline-dev nlohmann-json spdlog-dev boost-dev libgit2-dev libcbor-dev
RUN apk add lua5.4 lua5.4-socket lua5.4-filesystem
